import static org.junit.Assert.*;

import org.junit.Test;

// this test is for one particular case of 10 iteration
public class FibonacciTest {
	
	@Test //this tests to see whether the iteration counter is at 10 or not
	public void fib1test() {
		Fibonacci fibone = new Fibonacci();
		int iteration = fibone.iterationstep();
		
		assertEquals(10, iteration, 0);
	}
	
	@Test // this tests to see whether the numbers generated by the fibonacci sequence are correct by checking the total 
	public void fib2test() {
		Fibonacci fibtwo = new Fibonacci();
		int total = fibtwo.total_sequence(fibtwo.iterationstep());
		
		assertEquals(143, total, 0);
	}
}// end of test

/* Note:  
		- To test other iterations you must change the assertEquals in fib1test from 10 to the number of iteration steps you want to do.
		- To test other fibonacci sequences you must enter the right summed value, in fib2test of the proper iterated fibonacci sequence 
			and change it with the 143 value.
*/